# Базовий образ Node.js
FROM node:24

# Робоча директорія всередині контейнера
WORKDIR /app

# Копіюємо тільки файли залежностей для ефективного кешування
COPY package.json ./
COPY yarn.lock ./

# Встановлюємо залежності через Yarn
RUN yarn install --frozen-lockfile

# Копіюємо решту файлів проєкту
COPY . .

# Дозволяємо запуск від користувача node
RUN chown -R node:node /app

# Вказуємо порт, який слухає Vite (за замовчуванням)
EXPOSE 5173

# Переходимо на менш привілейованого користувача
USER node

# Запускаємо Vite dev сервер з доступом ззовні
CMD ["yarn", "dev", "--host"]
